#!/bin/bash

# Frontend Configuration Script for Raspberry Pi Backend
# This script helps you configure the frontend to connect to your Raspberry Pi backend

echo "=========================================="
echo "Frontend Configuration for Raspberry Pi"
echo "=========================================="
echo ""

# Get Raspberry Pi IP address
echo "Enter your Raspberry Pi's IP address:"
echo "(To find it, run 'hostname -I' on your Raspberry Pi)"
read -p "Raspberry Pi IP: " RPI_IP

# Validate IP format (basic check)
if [[ ! $RPI_IP =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    echo "Error: Invalid IP address format"
    exit 1
fi

# Get port (default 5000)
read -p "Backend port [5000]: " BACKEND_PORT
BACKEND_PORT=${BACKEND_PORT:-5000}

# Create the .env.production file
ENV_FILE="frontend/.env.production"
echo ""
echo "Creating $ENV_FILE..."

cat > "$ENV_FILE" << EOF
# Production environment variables for Raspberry Pi deployment
# This file was auto-generated by configure_frontend.sh

# Raspberry Pi Backend URL
VITE_API_URL=http://${RPI_IP}:${BACKEND_PORT}
EOF

echo "✓ Configuration file created successfully!"
echo ""
echo "Configuration:"
echo "  Backend URL: http://${RPI_IP}:${BACKEND_PORT}"
echo ""

# Test connection
echo "Testing connection to Raspberry Pi backend..."
if command -v curl &> /dev/null; then
    if curl -s -o /dev/null -w "%{http_code}" "http://${RPI_IP}:${BACKEND_PORT}/api/health" | grep -q "200"; then
        echo "✓ Successfully connected to backend!"
    else
        echo "⚠ Warning: Could not connect to backend at http://${RPI_IP}:${BACKEND_PORT}"
        echo "  Make sure the backend is running on your Raspberry Pi"
        echo "  Run: python3 backend/app.py"
    fi
else
    echo "⚠ curl not found, skipping connection test"
fi

echo ""
echo "Next steps:"
echo "1. Build the frontend: cd frontend && npm run build"
echo "2. Serve the frontend: npx serve -s dist -p 3000"
echo "3. Open http://localhost:3000 in your browser"
echo ""
echo "=========================================="
