@echo off
REM Frontend Configuration Script for Raspberry Pi Backend (Windows)
REM This script helps you configure the frontend to connect to your Raspberry Pi backend

echo ==========================================
echo Frontend Configuration for Raspberry Pi
echo ==========================================
echo.

REM Get Raspberry Pi IP address
set /p RPI_IP="Enter your Raspberry Pi's IP address (e.g., 192.168.1.100): "

REM Get port (default 5000)
set /p BACKEND_PORT="Backend port [5000]: "
if "%BACKEND_PORT%"=="" set BACKEND_PORT=5000

REM Create the .env.production file
set ENV_FILE=frontend\.env.production
echo.
echo Creating %ENV_FILE%...

(
echo # Production environment variables for Raspberry Pi deployment
echo # This file was auto-generated by configure_frontend.bat
echo.
echo # Raspberry Pi Backend URL
echo VITE_API_URL=http://%RPI_IP%:%BACKEND_PORT%
) > "%ENV_FILE%"

echo [OK] Configuration file created successfully!
echo.
echo Configuration:
echo   Backend URL: http://%RPI_IP%:%BACKEND_PORT%
echo.

REM Test connection
echo Testing connection to Raspberry Pi backend...
curl -s -o nul -w "%%{http_code}" "http://%RPI_IP%:%BACKEND_PORT%/api/health" | findstr "200" >nul
if %errorlevel%==0 (
    echo [OK] Successfully connected to backend!
) else (
    echo [WARNING] Could not connect to backend at http://%RPI_IP%:%BACKEND_PORT%
    echo   Make sure the backend is running on your Raspberry Pi
    echo   Run: python3 backend/app.py
)

echo.
echo Next steps:
echo 1. Build the frontend: cd frontend ^&^& npm run build
echo 2. Serve the frontend: npx serve -s dist -p 3000
echo 3. Open http://localhost:3000 in your browser
echo.
echo ==========================================
pause
